name: builder
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '*/60 * * * *'
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: netlify-deploy
      - name: Setup Node.js and install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      - name: Run build and parse RSS feeds
        run: npm run build --if-present
      - name: Commit latest build to ./output folder
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: netlify-deploy
          commit-message: 'Published latest changes to RSS feeds'
          force-add: 'true'
          files: output/*
          name: GitHub Action Bubo Bot
          email: action@github.com
